### ISSUE TITLE
Add support for SID instead of hard-coded system accounts

### ISSUE THREAD

**Issue by jugatsu** [chef/win32-taskscheduler#68]
## Description
For better support of localized versions of Windows, it would be better to use SID to determine if account actually system or not. Instead of hard-coded values
https://github.com/chef/win32-taskscheduler/blob/ole/lib/win32/windows/constants.rb#L4

For example on Russian version of Windows system account is 'СИСТЕМА', on French it's alslo localized, for example.

https://github.com/chef/chef/pull/7679

**Comment by Vasu1105** [comment]
Thank you @jugatsu @Nimesh-Msys  is working on this. So once we fix this. We can have a look at your PR on windows_task. As fix needs to be done on both the sides. We also identified task registration issue with BUILTIN\Users so we will be handling same here.

**Comment by Nimesh-Msys** [comment]
> Thank you @jugatsu @Nimesh-Msys is working on this. So once we fix this we can have a look at your PR on windows_task as fix needs to be done on both the sides. We also identified task registration issue with BUILTIN\Users so we will be handling same here.

Right, I've started working on it. Will make some changes in [this PR](https://github.com/chef/win32-taskscheduler/pull/69/) and update you shortly.
Thank you

**Comment by jugatsu** [comment]
Closed by #69
